/* Generated By:JJTree&JavaCC: Do not edit this line. TsurgeonParserConstants.java */
package edu.stanford.nlp.trees.tregex.tsurgeon;

public interface TsurgeonParserConstants {

  int EOF = 0;
  int DELETE = 4;
  int PRUNE = 5;
  int RELABEL = 6;
  int EXCISE = 7;
  int INSERT = 8;
  int MOVE = 9;
  int REPLACE = 10;
  int ADJOIN = 11;
  int ADJOIN_TO_HEAD = 12;
  int ADJOIN_TO_FOOT = 13;
  int COINDEX = 14;
  int SELECTION = 15;
  int IDENTIFIER = 16;
  int LABEL = 17;
  int LOCATION_RELATION = 18;
  int REGEX = 19;
  int QUOTEX = 20;
  int HASH_INTEGER = 21;
  int TREE_NODE_TERMINAL_LABEL = 22;
  int TREE_NODE_NONTERMINAL_LABEL = 23;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"delete\"",
    "\"prune\"",
    "\"relabel\"",
    "\"excise\"",
    "\"insert\"",
    "\"move\"",
    "\"replace\"",
    "\"adjoin\"",
    "\"adjoinH\"",
    "\"adjoinF\"",
    "\"coindex\"",
    "<SELECTION>",
    "<IDENTIFIER>",
    "<LABEL>",
    "<LOCATION_RELATION>",
    "<REGEX>",
    "<QUOTEX>",
    "<HASH_INTEGER>",
    "<TREE_NODE_TERMINAL_LABEL>",
    "<TREE_NODE_NONTERMINAL_LABEL>",
    "\"\\n\"",
    "\")\"",
  };

}
