/* Generated By:JavaCC: Do not edit this line. TregexParserConstants.java */
package edu.stanford.nlp.trees.tregex;

public interface TregexParserConstants {

  int EOF = 0;
  int RELATION = 4;
  int REL_W_STR_ARG = 5;
  int NUMBER = 6;
  int IDENTIFIER = 7;
  int BLANK = 8;
  int REGEX = 9;
  int VARNAME = 10;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<RELATION>",
    "<REL_W_STR_ARG>",
    "<NUMBER>",
    "<IDENTIFIER>",
    "\"__\"",
    "<REGEX>",
    "<VARNAME>",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"!\"",
    "\"@\"",
    "\"#\"",
    "\"%\"",
    "\"=\"",
    "\"~\"",
    "\"|\"",
    "\"&\"",
    "\"?\"",
    "\"[\"",
    "\"]\"",
  };

}
